### ISSUE TITLE
Configurable Space Branch

### ISSUE THREAD

**Issue by Matt-Jensen** [ModiiMedia/contentful-hugo#13]
Currently [space environments](https://www.contentful.com/developers/docs/concepts/multiple-environments/) are in alpha so don't think this feature is super urgent.

However the ability to configure the desired branch of a space, defaulting to master, from an environment variable will eventually be necessary for working with newer Contentful spaces.  That said I don't see any issue with this new feature being rolled out while Contentful get's it ironed out on their end.

Only potential gotcha I've found that should be documented is that tokens can be scoped to branches.

**Comment by joshmossas** [comment]
@Matt-Jensen this issue is now closed as of #26 

You can see in the [advanced config example](https://github.com/ModiiMedia/contentful-hugo#advanced-config-example) provided in the readme of how this can be accomplished.

Cheers

**Comment by Matt-Jensen** [comment]
Thank you @joshmossas, you're amazing!
