### ISSUE TITLE
SLUG in front-matter

### ISSUE THREAD

**Issue by dalemccrory** [ModiiMedia/contentful-hugo#19]
Is there an easy way to get the slug in the front-matter? I want to have Hugo URLs use my contentful slug, but I can't figure out how to add the slug into the exported data. Can you help?

Note: In the past, I have updated the Golang code for contentful-hugo to add it, but I lost my custom code to do it. Maybe I don't need custom code for this use case???

**Comment by joshmossas** [comment]
@dalemccrory what does you content model look like in Contentful?

If you create a field with the field ID ```slug``` contentful-hugo will place a slug field in the frontmatter and hugo urls will work normally. Contentful-hugo just creates frontmatter field names based on the field ID in Contentful so whatever field you want to appear in the frontmatter just name your field ID in Contentful to match the desired output.

See screenshots below

**Example Setup In Contentful**

![image](https://user-images.githubusercontent.com/31548851/80615279-192bec80-8a05-11ea-8aa8-830da414b1f0.png)

![image](https://user-images.githubusercontent.com/31548851/80615317-2648db80-8a05-11ea-99b3-844171f53626.png)

**Output from this setup**

![image](https://user-images.githubusercontent.com/31548851/80615872-db7b9380-8a05-11ea-9321-ee085d2cdc16.png)

**Comment by joshmossas** [comment]
> Note: In the past, I have updated the Golang code for contentful-hugo to add it, but I lost my custom code to do it. Maybe I don't need custom code for this use case???

@dalemccrory I just realized. Are you perhaps talking about a different library such as this one [https://github.com/thedodobird2/contentful-hugo](https://github.com/thedodobird2/contentful-hugo)?

This code for this repo is all Node.js. There is no Golang code.

If you'd like to try this library out though the setup is pretty simple and it generates frontmatter fields based on the field Ids in Contentful, which I think is preferable to the approach used in that other library I mentioned.

**Comment by dalemccrory** [comment]
You are correct, Josh. I will close this issue. :) Sorry, I put this up at
the end of my day. I will try out this library instead.
