### ISSUE TITLE
Add Support for Different Locales

### ISSUE THREAD

**Issue by joshmossas** [ModiiMedia/contentful-hugo#2]
Currently this module only pulls the default locale from Contentful. 

This feature should allow people to specify the locales they want in the **contentful-settings.yaml** file and then it would output the markdown files that will work with Hugo's [multilingual mode](https://gohugo.io/content-management/multilingual/).

Ideally each entry would be scanned to check if the items have actually been translated or not. Contentful returns the default language for locale fields that are left blank, so unless a check is in place a lot of "translated" files will be generated that just have the default language.

**Comment by joshmossas** [comment]
A workaround has been provided by https://github.com/ModiiMedia/contentful-hugo/pull/35, but it does create a lot of repetition in the config. So I'll leave this issue open until we create a more complete solution.

**Comment by bezoerb** [comment]
@joshmossas: The solution provided by #35 is broken (sorry for that). I added another PR to fix it. See #36

**Comment by joshmossas** [comment]
@bezoerb #36 has been merged into main. Apologies for the delay I've been on the road.

**Comment by joshmossas** [comment]
Additional considerations for locale support:

- Should translations be handled by filename (ie `something.fr.md`) or by directory (ie `en/articles/something.md` `fr/articles/something.md`)? Whatever we decide we need to make sure we can keep track of additions and deletions when running in server mode.
- What would configuration look like? Right now I'm thinking a simple global setting that takes an array of locales. Although if it's decided that we should handle translations with directories then we will need an additional setting to specify the directories. 
- Do we want to be able to ignore locales on certain content types? If that's the case it will also call for an additional setting.

**Comment by joshmossas** [comment]
Actually thinking it over handling translations via filename seems like the better option. If we take the directory approach it would conflict with the already existing `directory` setting which allows you to specify any location for the files. It's not limited to the "content" directory so we wouldn't be able to use root language folders unless we refactor that setting as well.

**Comment by joshmossas** [comment]
I have an implementation here if anyone wants to try it out and provide feedback: https://github.com/ModiiMedia/contentful-hugo/tree/multiple-locales-support

The readme has [updated instructions](https://github.com/ModiiMedia/contentful-hugo/tree/multiple-locales-support#localization-options) for working with locales as well.

I have yet to test it extensively when working with headless files and in server mode but it seems promising so far.

**Comment by joshmossas** [comment]
This feature has now been released as of [1.14.0](https://github.com/ModiiMedia/contentful-hugo/releases/tag/v1.14.0)
