### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by dsferruzza** [ModiiMedia/contentful-hugo#23]
Hi!

I believe that the package is broken on 1.7.0 because `package.json` references a `postinstall.js` file ([here](https://github.com/ModiiMedia/contentful-hugo/blob/master/package.json#L32)) whereas the file is actually named `postInstall.js` which makes the install fail on case sensitive systems.

**Comment by joshmossas** [comment]
Hello @dsferruzza thank you for reporting! This has now been fixed as of 1.7.2.
