### ISSUE TITLE
Question on Images

### ISSUE THREAD

**Issue by panzacoder** [ModiiMedia/contentful-hugo#57]
How do you handle image processing and responsive optimization? I'm having to re-invent the wheel in order to source images from Contentful while using a srcset or picture element.

How do you do this? Is there any way to source from Contentful AND use the Hugo Resource pipeline?

**Comment by joshmossas** [comment]
Hey @panzacoder for images sourced from Contentful I don't use the Hugo Resource pipeline I just use Contentful's [images API](https://www.contentful.com/developers/docs/references/images-api/#/reference/resizing-&-cropping) to resize and crop images.

So for responsive images it usually looks something like this

```go
// responsive img with 400w and 200w img urls
{{ with .Params.someImageField }}
    <img 
        srcset="{{ .url }}?w=400&h=400&fit=fill 400w, {{ .url }}?w=200&h=200&fit=fill 200w"
        sizes="(min-width: 600px) 400px, 200px"
        src="{{ .url }}?w=200&h=200&fit=fill"
        alt="{{ if .description }}{{ .description }}{{ else }}{{ .title }}"/>
{{ end }}
```

I've thought about having an option in the config to download assets and output them in a specified folder. I just haven't had a need for it so I haven't implemented it yet.
