### ISSUE TITLE
Line ending error

### ISSUE THREAD

**Issue by rosszurowski** [ModiiMedia/contentful-hugo#7]
Hi! Immediately after installing contentful-hugo v1.3.8 I ran into the following error:

```
$ contentful-hugo
env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
```

I've gotten this error both locally and on a Netlify build server.

Looking deeper, it seems the cli.js file has a CRLF line ending, rather than just an LF ending, which is causing bash to misinterpret `#!/usr/bin/env node` as `#!/usr/bin/env node\r`. Fixing this line ending resolved the error.

**Comment by joshmossas** [comment]
Hi @rosszurowski. I just want to confirm. Is this issue still happening for you in the latest version? (v1.3.10)

I work on work on Windows so I can't test as far as your machine goes, but it does work successfully on a Netlify build server for me.

Thanks!

**Comment by rosszurowski** [comment]
The issue is still happening. I tested installing via npm instead of yarn, which seems to have resolved it. This would also explain why it fails on my Netlify builds, because those are using yarn too.

Seems like this might actually be an issue for yarn regarding line-endings instead.

**Comment by joshmossas** [comment]
@rosszurowski huh that's really interesting. When I get some time I'll look into this further and see if I can get it working on both Yarn and NPM installations.

**Comment by Matt-Jensen** [comment]
Experiencing this bug on Linux and MacOS.  If it's helpful I was able fix this bug on MacOS by:

```sh
brew install dos2unix
find ./node_modules/contentful-hugo -name "*.js" | xargs sudo dos2unix
```

AFAIK this fixed the issue because it rewrote the line separator characters committed to be compatible with the host OS.  The `index.js` file may have line endings in CRLF (windows) instead of LS (unix)
